eureka:
  client:
    serviceUrl:
      defaultZone: https://eurika-service-production.up.railway.app/eureka/
  instance:
    prefer-ip-address: true
    ip-address: "accountmanagement-service-production.up.railway.app"
    hostname: "accountmanagement-service-production.up.railway.app"
    metadata-map:
      instanceId: "accountManagement-service:https://accountmanagement-service-production.up.railway.app"
    instance-id: "accountManagement-service:https://accountmanagement-service-production.up.railway.app"
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    status-page-url: "https://accountmanagement-service-production.up.railway.app/actuator/info"
    health-check-url: "https://accountmanagement-service-production.up.railway.app/actuator/health"
    home-page-url: "https://accountmanagement-service-production.up.railway.app"
